#!/usr/bin/env php
<?php

declare(strict_types=1);

use Celema\Console\Commands;
use Celema\Console\Runner;
use Celema\Server\FrankenPhp;
use Celema\Server\Server;

$root = dirname(__DIR__);
require $root . '/vendor/autoload.php';
chdir($root);

$docroot = __DIR__ . '/public';
$watch = ['app/**/*.{php,css,js}', 'src/**/*.php'];
$commands = new Commands([
	new Server($docroot, port: 1973, watch: $watch),
	new FrankenPhp($docroot, port: 1973, watch: $watch),
]);

exit(new Runner($commands)->run());
